### ISSUE TITLE
is the last case M1 or M2 aml?

### ISSUE THREAD

**Issue by jesswhitts** [genome/scrna_mutations#6]
Hi, 

In your tsv file with the clinical info it states the final case is M1, but in the case reports it says that case is M2, can you confirm which it is please?

Many thanks,
Jess

**Comment by chrisamiller** [comment]
My notes say M1, but I'm going to poke our clinical coordinator and see if I can get a definitive answer for you!

**Comment by chrisamiller** [comment]
Looks like this case is, indeed, M1.  I'm pushing a change to fix the typo in the case summary.  Thanks for catching that!

**Comment by jesswhitts** [comment]
Thanks! Some really nice data here :)
